name = "MC ASI Online"
author = "Poligorn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18d02d53e4ba7326514dc875ef2339f54ddf40985b394a5b85e5f8ceb163abbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
