name = "MC ASI Online"
author = "Poligorn"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e1252f8c65c0127936a8c308b8bea7144f9a905b203214ee6c0cf51a177a50f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
