name = "Aeronautics Ikaria"
author = "Poligorn"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f42ae69eafa2a7d0d478e447f3bf26b76e00c422f5f2eada0318e665ae10808"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
